[workspace]
members = [
    "bin",
    "sqlite-decoder",
    "sqlite-encoder",
    "sqlite-types",
    "sqlite-wal",
    "sqlite-table",
    "sqlite-opcode",
    "sqlite-pagecache",
    "sqlite-sql",
]
