[package]
name = "sqlite-decoder"
version = "0.1.0"
edition = "2021"
description = "SQLite WAL and database formats decoder"
authors = ["Sven Sauleau <sven@cloudflare.com>"]

[dependencies]
nom = "7"
sqlite-types = { path = "../sqlite-types" }
vlq = { package = "vlq-rust", version = "0.4" }
